name: Build Docker Images

on:
  workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@master
      - name: Build and push windows image
        env: 
          USER: ${{ secrets.DOCKER_USER }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        working-directory: .
        run: |
          docker login -u $env:USER -p $env:TOKEN
          docker build -f win64.dockerfile -m 6G -t gocnak/chaos-vsbuildtools:latest .
          docker push gocnak/chaos-vsbuildtools:latest
          docker logout
